---
###########################################################################################
#                                                                                         #
#                                                                                         #
#                       Digital Ocean Infrastructure config vars                          #
#                                                                                         #
#                                                                                         #
###########################################################################################

# Digital ocean API access token
do_oauth_token: 
# curl -X GET -silent "https://api.digitalocean.com/v2/account/keys" -H "Authorization: Bearer <<token>>" # to retrive the key
# Will list all the ssh key pub keys, ids, fingerprint and other relevent information. 
# Execute it on your terminal to retrive the required ssk_keys ids that would be able to ssh onto the droplets
# These ssh keys needs to be alrready created and present in digital ocean
ssh_keys: [20711668, 25140548]

# curl -X GET -silent "https://api.digitalocean.com/v2/images?per_page=999" -H "Authorization: Bearer <<token>>" | grep --color -E "ubuntu"
# Will get all the images and highlight ubuntu
images:
    # Debian should always be the first image
  - image: "53893572" # Ubuntu 18.04.3 (LTS) x64. 
    size: "s-1vcpu-1gb"
    region: "fra1"
  - image: "47384041" # fedora-30-x64
    size: "s-1vcpu-1gb"
    region: "ams3"
  - image: "47384041" # fedora-30-x64
    size: "s-1vcpu-1gb"
    region: "ams3"
  - image: "47384041" # fedora-30-x64
    size: "s-1vcpu-1gb"
    region: "ams3"
  - image: "53893572" # Ubuntu 18.04.3 (LTS) x64
    size: "s-1vcpu-1gb"
    region: "ams3"
  
