---
# ansible-playbook -v 001.spawn_droplets.yml

- name: create droplets
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    droplet_state: "present"
  roles:
    - setuphostsmachines/droplets