---
# ansible-playbook -v 001.despawn_droplets.yml

- name: create droplets
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    droplet_state: "absent"
  roles:    
    - setuphostsmachines/droplets
    - setuphostsmachines/init